# Generated by Django 5.2.12 on 2026-06-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_city_region_province_city_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.province'),
            preserve_default=False,
        ),
    ]
