# Generated by Django 5.2.12 on 2026-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_marca_producto_modelo_producto_tipo_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
